apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: yourdockerhubusername/mern-backend:1.0
          ports:
            - containerPort: 5050
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/mydb
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 5050
  type: ClusterIP
